[project]
name = "organise-files"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "toml>=0.10.2",
    "typer>=0.15.1",
]
