name: Build and Publish Windows Release

on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow on any tag push that starts with 'v' (e.g., v1.0.0)

jobs:
  build:
    runs-on: windows-latest  # Use Windows-based environment for the build

    steps:
    # Check out the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: 3.12  # Use the version you need

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install any dependencies in your project

    # Install PyInstaller (if not already in requirements.txt)
    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    # Build the application with PyInstaller
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile main.py  # Adjust with your script name
        ren dist\main.exe dist\gniphyl.exe  # Rename the file on Windows

    # Create a new GitHub Release and upload the executable
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/gniphyl.exe  # Ensure the correct file path
